### ISSUE TITLE
Es fehlt, dass der Key am Ende angezeigt wird

### ISSUE THREAD

**Issue by rubo77** [rubo77/site-ffki#1]
Hab dazu dies gefunden:

gluon-config-mode:pubkey now have to show the fastd public key itself

i18n/

```
The translations of gluon-config-mode:pubkey now have to show the fastd public key itself if desired, making the formatting of the key and whether it is shown at all configurable. To retain the old format, add <p> to the beginning of your translations and append:

 "</p>"
 "<div class=\"the-key\">"
 " # <%= hostname %>"
 " <br/>"
 "<%= pubkey %>"
 "</div>"
```

**Comment by do9xe** [comment]
You know, that this is just yor personal fork, right? Please commit your changes at the ffki-gitserver.

**Comment by rubo77** [comment]
I cannot start a discussion in our kiel git repo. and this is an exact copy.

please look into this problem:

the key is not shown at the end of config mode.

I thought it would be quite handy to discuss this here because you can directly linke to the source code. not sure how to solve this problem

**Comment by do9xe** [comment]
We have a Mailinglist for that.

**Comment by do9xe** [comment]
Done.

**Comment by rubo77** [comment]
Cool :)
