### ISSUE TITLE
2016.1.5 - Your site configuration did not pass validation.

### ISSUE THREAD

**Issue by rubo77** [rubo77/site-ffki#3]
dies sind die letzten fehler beim Bauen:

```
/home/foo/freifunk/build/gluon/Makefile:347: recipe for target 'prepare' failed
make[1]: Leaving directory '/home/foo/freifunk/build/gluon/build/ar71xx-generic/openwrt'
Makefile:77: recipe for target 'all' failed
```

siehe http://paste.debian.net/712860/

**Comment by Tarnatos** [comment]
Moin,

hier schlägt schon das Bauen der toolchain fehl. Das kann schon mal passieren, wenn einzelne Downloads nicht erreichbar sind. Taucht aber nicht im Log auf.

Habt ihr mit einem frischen Klon gebaut? Oder mit make clean $target zumindest vorher die Verzeichnisse aufgeräumt?

Das Paket fastd-traffic-status benötigt ihr in Kiel nicht. Das ist für die Traffic Auswertung auf dem Hamburger Statistik Server. Wenn es mit rein soll müßt ihr es manuell nach gluon/package/ kopieren. Der Git Sync via .modules will irgendwie nicht.

**Comment by rubo77** [comment]
Wieso muss   #gluon-mesh-vpn-fastd raus?

Die URL sollte bei in-kiel.de bleiben, da wir die selbst kontrollieren

**Comment by Tarnatos** [comment]
Das Paket wurde von tokûdan geschrieben, damit die Nodes Traffic Statistiken in einem Forma auswerfen das er mit seiner Grafana Instanz auf statistik.hamburg.freifunk.net auswerten kann.

Kiel hat keine Grafana Instanz.

**Comment by rubo77** [comment]
Sven meint: das Bauen geht nur wenn der definierte opkg Server von innerhalb und von ausserhalb des Freifunks erreichbar ist und der Rechner, auf dem man baut, im Freifunk ist

**Comment by xmaka** [comment]
Kann ich mir nicht vorstellen: Wie soll eine neue Community entstehen? Wie entstand die erste Community?

**Comment by Tarnatos** [comment]
Wie sag ich das jetzt...

Käse! Mein Build Server hängt weder im Freifunk Netz noch erreicht er den angegebenen opkg Server.

Völlig egal. Die opkg Anweisung muss in korrektem json geschrieben sein. Mehr prüft make nicht. Du kannst da auch bild.de als opkg server eintragen das ist make wurscht.

**Comment by Tarnatos** [comment]
Wie gesagt der Fehler oben liegt an der Toolchain. Das kann z.B. an einem der Kaskadierten gits sein das nicht erreichbar ist.

Einfach öfter probieren. Ich habe euch meinen build Ordner gepackt. Da ist die toolchain drin. Den könnt ihr nehmen. Einfach per Matrix anschreiben.

**Comment by rubo77** [comment]
not sure, if it is fixed yet

**Comment by rubo77** [comment]
ev. auch hier der grund: https://github.com/fsteinel/gluon-packages/issues/1

**Comment by rubo77** [comment]
ist alles korrigiert in https://github.com/rubo77/gluon-packages

(Siehe commit history dort)
