### ISSUE TITLE
Kommentar macht site.mk kaputt

### ISSUE THREAD

**Issue by TobleMiner** [rubo77/site-ffki#4]
Der Kommentar
`#gluon-mesh-vpn-fastd \`
zerstört die site.mk.
Alle Zeilen in der Config nach dieser Zeile werden einfach ignoriert. \ setzt die Zeilen alle zu einer großen Zeile zusammen. Wenn da eine `#` drinsteht ist der gesamte Rest Kommentar. Das ist eventuell auch related zu #3

**Comment by TobleMiner** [comment]
Außerdem enthält die config `fastd-traffic-status`. Dieses Paket wird so weit ich das sehe von nichts referenziert und compiled nicht, da nicht vohanden.

**Comment by rubo77** [comment]
also meinst du, dass zeile 21 hier
https://github.com/rubo77/site-ffki/pull/5/files#diff-ee66465f633623903a102ce0983dd48dL21
zeile 22 mit auskomentiert?

das sollte @Tarnatos dann ev.  auch beachten in ffnord

**Comment by TobleMiner** [comment]
Mh, durch den Kommentar werden alle weitern mit `\` verbundenen Zeilen nicht mehr beachtet. Ich hatte mir gerade ein neues Gluon mit der siteconf von hier gebaut und mich gewundert warum Pakete wie `gluon-status-page` fehlen.

**Comment by do9xe** [comment]
Das tut sie definitiv, eigentlich sogar alle Zeilen danach. Ein Backslash bedeutet, dass unabhängig von einem Zeilenumbruch, die Zeile in der nächsten Zeile weiter geführt wird. Ist in C und anderen Sprechen auch so. Das ist nur der Übersicht halber.

**Comment by rubo77** [comment]
Stimmt nicht so ganz: ein kommentar bricht nur die Kette der verbundenen Zeilen, die Zeilen danach werden als normale befehlszeilen interpretiert:

```
# echo 'echo test 1 \
2 \
#3 \
hier krachts \
4 \
5'>a
root@gespensterklumpen:/tmp# bash a
test 1 2
a: Zeile 4: hier: Befehl nicht gefunden
```

kommentare mittendrin würden so gehen:

```
echo zeile 1 \
zeile 2 \
`: commented line 3 `\
hier krachts nicht mehr \
zeile 5 \
zeile6
```
